const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.X,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Cnds.OnEnded
	];
};
self.C3_JsPropNameTable = [
	{Text: 0},
	{TextInput: 0},
	{Audio: 0},
	{Fade: 0},
	{testbox: 0},
	{bonobo: 0},
	{IntroText: 0},
	{White: 0},
	{Loading: 0},
	{Planet: 0},
	{MoveTo: 0},
	{Net: 0},
	{Hp: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{Egg: 0},
	{Points: 0},
	{FaceHugger: 0},
	{Hand: 0},
	{Block: 0},
	{Block2: 0},
	{Block3: 0},
	{Base: 0},
	{Touch: 0},
	{testbox2: 0},
	{Keyboard: 0},
	{Xenomorph: 0},
	{Block4: 0},
	{Points2: 0},
	{ClickToStart: 0},
	{Apple: 0},
	{testbox222: 0},
	{xmirambox: 0},
	{giphy: 0},
	{IntroText2: 0},
	{IntroText3: 0},
	{Sprite: 0},
	{Phys: 0},
	{Lost: 0},
	{CountDownTimer: 0},
	{Timer: 0},
	{RunGame: 0},
	{RunIntro: 0},
	{XValue: 0}
];

self.InstanceType = {
	Text: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Audio: class extends self.IInstance {},
	testbox: class extends self.ISpriteInstance {},
	bonobo: class extends self.ISpriteInstance {},
	IntroText: class extends self.ITextInstance {},
	White: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	Planet: class extends self.ISpriteInstance {},
	Net: class extends self.ISpriteInstance {},
	Egg: class extends self.ISpriteInstance {},
	Points: class extends self.ITextInstance {},
	FaceHugger: class extends self.ISpriteInstance {},
	Hand: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	Block2: class extends self.ISpriteInstance {},
	Block3: class extends self.ISpriteInstance {},
	Base: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	testbox2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Xenomorph: class extends self.ISpriteInstance {},
	Block4: class extends self.ISpriteInstance {},
	Points2: class extends self.ITextInstance {},
	ClickToStart: class extends self.ISpriteInstance {},
	Apple: class extends self.ISpriteInstance {},
	testbox222: class extends self.ISpriteInstance {},
	xmirambox: class extends self.ISpriteInstance {},
	giphy: class extends self.ISpriteInstance {},
	IntroText2: class extends self.ITextInstance {},
	IntroText3: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Phys: class extends self.ISpriteInstance {}
}